# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NGQyZmE0YjJjNTBmM2MyYjcyOGI4ZGY0ODJjMmQwYjA1Yjk5NzFiN2FiZGQwNDdkMTZhY2FjM2ZiNzMxYWE4OWE2MDUwYjUxZjQ1MzM0NjQwMjI0NTFiMWIwMzBlZTU2MmU1MTg4MjBhZjU5YTUyZTNjZTI3Mjg2ZmJiZDQ2OWI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
